### ISSUE TITLE
Wrong argument error in Chef 11.16.4 on 2.6.2 release

### ISSUE THREAD

**Issue by martinisoft** [chef-cookbooks/aws#108]
Running version 2.6.2 with Chef 11.16.4 on Ubuntu 14.04.1

```
================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/go-remote-control/recipes/default.rb
  ================================================================================

  ArgumentError
  -------------
  wrong number of arguments (1 for 0)

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/aws/recipes/default.rb:22:in `block in from_file'
    /var/chef/cache/cookbooks/aws/recipes/default.rb:20:in `from_file'
    /var/chef/cache/cookbooks/go-remote-control/recipes/install.rb:18:in `from_file'
    /var/chef/cache/cookbooks/go-remote-control/recipes/default.rb:10:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/aws/recipes/default.rb:

   15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   16:  # See the License for the specific language governing permissions and
   17:  # limitations under the License.
   18:  #
   19:
   20:  chef_gem 'aws-sdk' do
   21:    version node['aws']['aws_sdk_version']
   22>>   compile_time true if respond_to?(:compile_time)
   23:    action :install
   24:  end
   25:
   26:  require 'aws-sdk'
   27:
```

**Comment by martinisoft** [comment]
Sadly 44aaee1afb8395b0527d9f056b10e6cde51e13f4 does not resolve my issue:

```
  ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/chef-vault/recipes/default.rb
  ================================================================================

  ArgumentError
  -------------
  wrong number of arguments (1 for 0)

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/chef-vault/recipes/default.rb:23:in `block in from_file'
    /var/chef/cache/cookbooks/chef-vault/recipes/default.rb:21:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/chef-vault/recipes/default.rb:

   16:  # distributed under the License is distributed on an "AS IS" BASIS,
   17:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   18:  # See the License for the specific language governing permissions and
   19:  # limitations under the License.
   20:
   21:  chef_gem 'chef-vault' do
   22:    version node['chef-vault']['version']
   23>>   compile_time true if Chef::Resource::ChefGem.method_defined?(:compile_time)
   24:  end
   25:
   26:  require 'chef-vault'
   27:
```

**Comment by martinisoft** [comment]
44aaee1afb8395b0527d9f056b10e6cde51e13f4 did not fix this for me either:

```
================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/aws/recipes/default.rb
  ================================================================================

  ArgumentError
  -------------
  wrong number of arguments (1 for 0)

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/aws/recipes/default.rb:22:in `block in from_file'
    /var/chef/cache/cookbooks/aws/recipes/default.rb:20:in `from_file'
    /var/chef/cache/cookbooks/go-remote-control/recipes/install.rb:18:in `from_file'
    /var/chef/cache/cookbooks/go-remote-control/recipes/default.rb:10:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/aws/recipes/default.rb:

   15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   16:  # See the License for the specific language governing permissions and
   17:  # limitations under the License.
   18:  #
   19:
   20:  chef_gem 'aws-sdk' do
   21:    version node['aws']['aws_sdk_version']
   22>>   compile_time true if Chef::Resource::ChefGem.method_defined?(:compile_time)
   23:    action :install
   24:  end
   25:
   26:  require 'aws-sdk'
   27:
```

**Comment by scalp42** [comment]
I confirm it breaks with `if Chef::Resource::ChefGem.method_defined?(:compile_time)`:

```ruby
include_recipe 'chef-sugar'
include_recipe 'aws'
```

Vagrant run:

```
==> zs1: [2015-02-19T06:08:21+00:00] INFO: *** Chef 11.16.4 ***
==> zs1: [2015-02-19T06:08:21+00:00] INFO: Chef-client pid: 3555
==> zs1: [2015-02-19T06:08:21+00:00] WARN: [DEPRECATION] Plugin at /etc/chef/ohai_plugins/vagrant.rb is a version 6 plugin. Version 6 plugins will not be supported in future releases of Ohai. Please upgrade your plugin to version 7 plugin syntax. For more information visit here: docs.opscode.com/ohai_custom.html
==> zs1: [2015-02-19T06:08:27+00:00] INFO: Setting the run_list to ["recipe[mesosphere::test]"] from CLI options
==> zs1: [2015-02-19T06:08:27+00:00] INFO: Run List is [recipe[mesosphere::test]]
==> zs1: [2015-02-19T06:08:27+00:00] INFO: Run List expands to [mesosphere::test]
==> zs1: [2015-02-19T06:08:27+00:00] INFO: Starting Chef Run for mesosphere-scalp-vagrant-vbox-1
==> zs1: [2015-02-19T06:08:27+00:00] INFO: Running start handlers
==> zs1: [2015-02-19T06:08:27+00:00] INFO: Start handlers complete.
==> zs1: [2015-02-19T06:08:28+00:00] INFO: HTTP Request Returned 404 Object Not Found:
==> zs1: [2015-02-19T06:08:29+00:00] INFO: Loading cookbooks [mesosphere@0.0.99, apt@2.6.1, aws@2.6.4, cron@1.6.1, docker@0.36.0, aufs@0.1.1, modules@0.2.0, device-mapper@0.1.0, git@4.1.0, build-essential@2.1.3, dmg@2.2.2, runit@1.5.16, yum@3.5.3, yum-epel@0.6.0, windows@1.36.3, chef_handler@1.1.6, golang@1.5.0, homebrew@1.12.0, iptables@0.14.1, lxc@2.0.0, dpkg_autostart@0.1.12, polipo@0.1.0, iptables-ng@2.2.5, sysctl@0.6.2, ohai@2.0.1, exhibitor@0.4.0, java@1.31.0, zookeeper@2.5.1, hostsfile@2.4.5, ntp@1.7.0, xml@1.2.9, chef-sugar@2.5.0]
==> zs1: [2015-02-19T06:08:35+00:00] INFO: Storing updated cookbooks/aws/recipes/default.rb in the cache.
==> zs1: /var/chef/cache/cookbooks/homebrew/libraries/homebrew_package.rb:26: warning: toplevel constant Homebrew referenced by Chef::Provider::Package::Homebrew
==> zs1:
==> zs1: ================================================================================
==> zs1: Recipe Compile Error in /var/chef/cache/cookbooks/mesosphere/recipes/test.rb
==> zs1: ================================================================================
==> zs1:
==> zs1:
==> zs1: ArgumentError
==> zs1: -------------
==> zs1: wrong number of arguments (1 for 0)
==> zs1:
==> zs1:
==> zs1: Cookbook Trace:
==> zs1: ---------------
==> zs1:   /var/chef/cache/cookbooks/aws/recipes/default.rb:22:in `block in from_file'
==> zs1:
==> zs1:   /var/chef/cache/cookbooks/aws/recipes/default.rb:19:in `from_file'
==> zs1:
==> zs1:   /var/chef/cache/cookbooks/mesosphere/recipes/test.rb:3:in `from_file'
==> zs1:
==> zs1:
==> zs1: Relevant File Content:
==> zs1: ----------------------
==> zs1: /var/chef/cache/cookbooks/aws/recipes/default.rb:
==> zs1:
==> zs1:
==> zs1:
==> zs1:  15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
==> zs1:
==> zs1:  16:  # See the License for the specific language governing permissions and
==> zs1:
==> zs1:  17:  # limitations under the License.
==> zs1:
==> zs1:  18:  #
==> zs1:
==> zs1:  19:  chef_gem 'aws-sdk' do
==> zs1:  20:    version node['aws']['aws_sdk_version']
==> zs1:  21:    if Chef::Resource::ChefGem.method_defined?(:compile_time)
==> zs1:  22>>     compile_time true
==> zs1:  23:    end
==> zs1:  24:    action :install
==> zs1:  25:  end
==> zs1:  26:
==> zs1:  27:  require 'aws-sdk'
==> zs1:  28:
==> zs1:
==> zs1: [2015-02-19T06:08:37+00:00] ERROR: Running exception handlers
==> zs1: [2015-02-19T06:08:37+00:00] ERROR: Exception handlers complete
==> zs1: [2015-02-19T06:08:37+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> zs1: [2015-02-19T06:08:37+00:00] ERROR: wrong number of arguments (1 for 0)
==> zs1: [2015-02-19T06:08:37+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by scalp42** [comment]
@someara @martinisoft please have a look at https://github.com/opscode-cookbooks/aws/pull/110

**Comment by tas50** [comment]
This should be fixed in the later 2.X and the 3.0 release.
