### ISSUE TITLE
aws_elastic_lb - undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by dpattmann** [chef-cookbooks/aws#210]
Version 2.9.2 (Version 2.6.2 works fine)
Ubuntu 14.04
Chef: 12.6.0

```bash
================================================================================
Error executing action `register` on resource 'aws_elastic_lb[my-lb]'
================================================================================

NoMethodError
-------------
undefined method `[]' for nil:NilClass

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/aws/providers/elastic_lb.rb:6:in `block (2 levels) in class_from_file'
/var/chef/cache/cookbooks/aws/providers/elastic_lb.rb:4:in `block in class_from_file'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/myaws/recipes/_aws-lb.rb

 11: aws_elastic_lb 'myaws_lb' do
 12:   aws_access_key aws['aws_access_key_id']
 13:   aws_secret_access_key aws['aws_secret_access_key']
 14:   name node['myaws']['aws']['loadbalancer']
 15:   action :register
 16: end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/myaws/recipes/_aws-lb.rb:11:in `from_file'

aws_elastic_lb("my-lb") do
  action [:register]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :aws_elastic_lb
  cookbook_name "myaws"
  recipe_name "_aws-lb"
  aws_access_key "XXXXXXXXXXXXXXXXXXXX"
  aws_secret_access_key "XXXXXXXXXXXXXXXXXXXXXXXXXX"
end

[2016-02-04T12:38:18+00:00] INFO: Running queued delayed notifications before re-raising exception
NoMethodError: aws_elastic_lb[my-lb] (myaws::_aws-lb line 11) had an error: NoMethodError: undefined method `[]' for nil:NilClass
	from /var/chef/cache/cookbooks/aws/providers/elastic_lb.rb:6:in `block (2 levels) in class_from_file'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/mixin/why_run.rb:52:in `call'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/mixin/why_run.rb:52:in `add_action'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider.rb:175:in `converge_by'
	from /var/chef/cache/cookbooks/aws/providers/elastic_lb.rb:4:in `block in class_from_file'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider/lwrp_base.rb:87:in `instance_eval'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider/lwrp_base.rb:87:in `block in action'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider.rb:144:in `run_action'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource.rb:596:in `run_action'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:74:in `run_action'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:106:in `block (2 levels) in converge'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:106:in `each'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:106:in `block in converge'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:105:in `converge'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/shell/ext.rb:236:in `run_chef'
	from (irb#1):1chef:recipe (12.6.0)> 

```

**Comment by mulakkalfaizal** [comment]
add the region name in attribute files in aws cookbook.

it will work.

**Comment by dpattmann** [comment]
@mulakkalfaizal - Thanks!

I added ```default['aws']['region'] = 'eu-west-1'``` and now it works.
