### ISSUE TITLE
Option mount_point_mode must be a kind of [String]!  You passed 493..

### ISSUE THREAD

**Issue by scalp42** [chef-cookbooks/aws#212]
I'm not using the `aws_ebs_raid` resource, but I'm seeing this warning in log:

```
[2016-02-13T01:57:46+00:00] WARN: Default value 493 is invalid for property mount_point_mode of resource aws_ebs_raid. In Chef 13 this will become an error: Option mount_point_mode must be a kind of [String]!  You passed 493.. at /var/chef/cache/cookbooks/aws/resources/ebs_raid.rb:28:in `class_from_file' at /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
```

Using `Chef 12.7.2` here.

**Comment by whiteadam** [comment]
Same thing here, not sure what it is.

**Comment by gpurrenhage** [comment]
I resolved the warning in my systems by adding quotes around the 00755 value at https://github.com/chef-cookbooks/aws/blob/master/resources/ebs_raid.rb#L28

**Comment by pkang** [comment]
:+1: Yes, please fix.

**Comment by tas50** [comment]
Fixed with @gpurrenhage's suggested change. The improved validation in Chef 12.7.X is throwing the error as expected here
