### ISSUE TITLE
Documentation: delete_on_termination requires ec2:ModifyInstanceAttribute

### ISSUE THREAD

**Issue by eherot** [chef-cookbooks/aws#241]
Otherwise you get this:

```
           ================================================================================
           Error executing action `attach` on resource 'aws_ebs_volume[vol1]'
           ================================================================================

           Aws::EC2::Errors::UnauthorizedOperation
           ---------------------------------------
           You are not authorized to perform this operation.

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/aws/providers/ebs_volume.rb:321:in `mark_delete_on_termination'
           /tmp/kitchen/cache/cookbooks/aws/providers/ebs_volume.rb:76:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/aws/providers/ebs_volume.rb:73:in `block in class_from_file'
```

**Comment by tas50** [comment]
@eherot Any chance you want to cut a PR to add this to the readme?

**Comment by eherot** [comment]
👆
