### ISSUE TITLE
Chef 13 Error for ec2_hints

### ISSUE THREAD

**Issue by kylegoch** [chef-cookbooks/aws#282]
### Cookbook version
4.2.2
### Chef-client version
13.0.113
### Platform Details
Ubuntu 16.04
### Scenario:
Run ec2_hints recipe
### Steps to Reproduce:
Run ec2_hints recipe with chef client 13.0.113
### Expected Result:
Recipe should run without error
### Actual Result:
Chef error occurs:
```
Recipe: aws::ec2_hints
  * ohai_hint[ec2] action create
    
    ================================================================================
    Error executing action `create` on resource 'ohai_hint[ec2]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `first' for nil:NilClass
    
    Cookbook Trace:
    ---------------
    /opt/kitchen/cache/cookbooks/ohai/resources/hint.rb:27:in `block in class_from_file'
    /opt/kitchen/cache/cookbooks/ohai/resources/hint.rb:53:in `block in after_created'
    /opt/kitchen/cache/cookbooks/ohai/resources/hint.rb:52:in `each'
    /opt/kitchen/cache/cookbooks/ohai/resources/hint.rb:52:in `after_created'
    /opt/kitchen/cache/cookbooks/aws/recipes/ec2_hints.rb:20:in `from_file'
    /opt/kitchen/cache/cookbooks/chef_base/recipes/default.rb:8:in `from_file'
    /opt/kitchen/cache/cookbooks/chef_role_jenkins/recipes/default.rb:8:in `from_file'
    
    Resource Declaration:
    ---------------------
    # In /opt/kitchen/cache/cookbooks/aws/recipes/ec2_hints.rb
    
     20: ohai_hint 'ec2' do
     21:   compile_time true
     22: end
    
    Compiled Resource:
    ------------------
    # Declared in /opt/kitchen/cache/cookbooks/aws/recipes/ec2_hints.rb:20:in `from_file'
    
    ohai_hint("ec2") do
      action [:create]
      default_guard_interpreter :default
      declared_type :ohai_hint
      cookbook_name "aws"
      recipe_name "ec2_hints"
      compile_time true
      hint_name "ec2"
    end
    
    System Info:
    ------------
    chef_version=13.0.113
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
    program_name=chef-client worker: ppid=54;start=19:58:44;
    executable=/opt/chef/embedded/bin/chef-client
    
  
  ================================================================================
  Recipe Compile Error in /opt/kitchen/cache/cookbooks/chef_role_jenkins/recipes/default.rb
  ================================================================================
  
  NoMethodError
  -------------
  ohai_hint[ec2] (aws::ec2_hints line 20) had an error: NoMethodError: undefined method `first' for nil:NilClass
  
  Cookbook Trace:
  ---------------
    /opt/kitchen/cache/cookbooks/ohai/resources/hint.rb:27:in `block in class_from_file'
    /opt/kitchen/cache/cookbooks/ohai/resources/hint.rb:53:in `block in after_created'
    /opt/kitchen/cache/cookbooks/ohai/resources/hint.rb:52:in `each'
    /opt/kitchen/cache/cookbooks/ohai/resources/hint.rb:52:in `after_created'
    /opt/kitchen/cache/cookbooks/aws/recipes/ec2_hints.rb:20:in `from_file'
    /opt/kitchen/cache/cookbooks/chef_base/recipes/default.rb:8:in `from_file'
    /opt/kitchen/cache/cookbooks/chef_role_jenkins/recipes/default.rb:8:in `from_file'
  
  Relevant File Content:
  ----------------------
  /opt/kitchen/cache/cookbooks/ohai/resources/hint.rb:
  
   20:    rescue JSON::ParserError
   21:      Chef::Log.debug("Could not parse JSON in ohai hint at #{ohai_hint_path}. It's probably an empty hint file")
   22:      return nil
   23:    end
   24:  end
   25:  
   26:  action :create do
   27>>   directory ::Ohai::Config[:hints_path].first do
   28:      action :create
   29:      recursive true
   30:    end
   31:  
   32:    file ohai_hint_path do
   33:      action :create
   34:      content build_content
   35:    end
   36:  end
  
  System Info:
  ------------
  chef_version=13.0.113
  platform=ubuntu
  platform_version=16.04
  ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
  program_name=chef-client worker: ppid=54;start=19:58:44;
  executable=/opt/chef/embedded/bin/chef-client
  
  
  Running handlers:
[2017-04-10T19:59:19+00:00] ERROR: Running exception handlers
  Running handlers complete
[2017-04-10T19:59:19+00:00] ERROR: Exception handlers complete
  Chef Client failed. 0 resources updated in 35 seconds
[2017-04-10T19:59:19+00:00] FATAL: Stacktrace dumped to /opt/kitchen/cache/chef-stacktrace.out
[2017-04-10T19:59:19+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-04-10T19:59:19+00:00] ERROR: ohai_hint[ec2] (aws::ec2_hints line 20) had an error: NoMethodError: undefined method `first' for nil:NilClass
[2017-04-10T19:59:19+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by tas50** [comment]
The issue here is actually in the ohai cookbook, but I've released an updated version of the aws cookbook (5.0) that requires the new ohai cookbook to fix this.
