### ISSUE TITLE
Chef 13 error on aws_resource_tag

### ISSUE THREAD

**Issue by Stromweld** [chef-cookbooks/aws#283]
### Cookbook version
4.2.2

### Chef-client version
13.0.113

### Platform Details
Latest CentOS 6 and 7 on AWS Cloud

### Scenario:
updating resource tags in aws

### Steps to Reproduce:
chef-client with wrapper to create aws tags for ec2 instances

### Expected Result:
AWS ec2 instance tag being updated with  key value.

### Actual Result:
This worked before with chef-client 12.19.36 but with 13.0.113 we get this runtime error:

```
Recipe: aws-tagging-nativex::default
  * chef_gem[aws-sdk] action install (up to date)
  * aws_resource_tag[i-0868edf9ce8332c2a] action update

    ================================================================================
    Error executing action `update` on resource 'aws_resource_tag[i-0868edf9ce8332c2a]'
    ================================================================================

    NameError
    ---------
    uninitialized constant Chef::Resource::AwsResourceTag

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/aws/providers/resource_tag.rb:80:in `load_current_resource'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/aws-tagging-nativex/recipes/default.rb

     19:   aws_resource_tag tag[:awsid] do
     20:     tags(
     21:       tag[:key] => tag[:value]
     22:     )
     23:   end
     24: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/aws-tagging-nativex/recipes/default.rb:19:in `block in from_file'

    aws_resource_tag("i-0868edf9ce8332c2a") do
      action [:update]
      default_guard_interpreter :default
      declared_type :aws_resource_tag
      cookbook_name "aws-tagging-nativex"
      recipe_name "default"
      tags {"CostCenter"=>"aerospike-misc-prod"}
    end

    System Info:
    ------------
    chef_version=13.0.113
    platform=centos
    platform_version=6.8
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
    program_name=chef-client worker: ppid=9665;start=19:04:37;
    executable=/opt/chef/bin/chef-client

Recipe: timezone-ii::rhel
  * execute[tzdata-update] action run
    - execute /usr/sbin/tzdata-update

Running handlers:
[2017-04-10T19:05:02-05:00] ERROR: Running exception handlers
Running handlers complete
[2017-04-10T19:05:02-05:00] ERROR: Exception handlers complete
Chef Client failed. 16 resources updated in 25 seconds
[2017-04-10T19:05:02-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-04-10T19:05:02-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-04-10T19:05:02-05:00] ERROR: aws_resource_tag[i-0868edf9ce8332c2a] (aws-tagging-nativex::default line 19) had an error: NameError: uninitialized constant Chef::Resource::AwsResourceTag
[2017-04-10T19:05:02-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by son1cc** [comment]
+1

**Comment by erulabs** [comment]
+1

**Comment by tas50** [comment]
Fix is merged. Release going out today
