### ISSUE TITLE
No resource or method named `do_s3_file' for `LWRP resource aws_s3_file from cookbook aws action provider.

### ISSUE THREAD

**Issue by onetwopunch** [chef-cookbooks/aws#310]
### Cookbook version
v7.1.2

### Chef-client version
```
$ chef-solo --version
Chef: 12.5.1
```

### Platform Details
Ubuntu 14.04

### Scenario:
I'm trying to access an AWS cloud file on a public bucket in S3 I am able to do it with the CLI, but not not with the AWS cookbook. This happened recently since we've been doing some permissions changes and now do not have the need for `aws_secret_access_key` and `aws_access_key`. It seems that removing them has caused issues with the cookbook. In production it works fine (using instance profile credentials) but in Vagrant, it fails with credentials in `~/.aws/credentials`.
### Expected Result:

I expect the public file to be downloaded from the public S3 bucket. 

### Actual Result/Steps to repro:
```

    ================================================================================
    Error executing action `create` on resource 'aws_s3_file[/etc/geo/GeoLite2-City.mmdb]'
    ================================================================================

    NoMethodError
    -------------
    No resource or method named `do_s3_file' for `LWRP resource aws_s3_file from cookbook aws action provider "/etc/geo/GeoLite2-City.mmdb"'

    Cookbook Trace:
    ---------------
    /opt/kitchen/librarian-cookbooks/aws/resources/s3_file.rb:34:in `block in class_from_file'
    /opt/kitchen/librarian-cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /opt/kitchen/librarian-cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /opt/kitchen/librarian-cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /opt/kitchen/librarian-cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /opt/kitchen/librarian-cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

    Resource Declaration:
    ---------------------
    # In /opt/kitchen/site-cookbooks/outreach_geo/recipes/default.rb

     21: aws_s3_file node['outreach']['geo']['maxminddb']['unzipped'] do
     22:   bucket 'outreach-operations'
     23:   remote_path "#{node.chef_environment}/geo/GeoLite2-City.mmdb"
     24:   region 'us-west-2'
     25:   owner node['outreach']['geo']['user']
     26:   group node['outreach']['geo']['group']
     27:   mode '0640'
     28: end

    Compiled Resource:
    ------------------
    # Declared in /opt/kitchen/site-cookbooks/outreach_geo/recipes/default.rb:21:in `from_file'

    aws_s3_file("/etc/geo/GeoLite2-City.mmdb") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :aws_s3_file
      cookbook_name :outreach_geo
      recipe_name "default"
      bucket "outreach-operations"
      remote_path "development/geo/GeoLite2-City.mmdb"
      region "us-west-2"
      owner "vagrant"
      group "vagrant"
      mode "0640"
    end
```

**Comment by tas50** [comment]
You’ll need to upgrade to a newer Chef client. 12.5 is no longer supported by this cookbook
