### ISSUE TITLE
opsworks (chef-solo) aws_ebs_volume: "RuntimeError: Volume no longer exists"

### ISSUE THREAD

**Issue by ashelley** [chef-cookbooks/aws#69]
I'm attempting to use the aws_ebs_volume resource to attach an ebs volume to an opsworks instance at boot.  However, when the custom recipe runs I get the following message:

```

================================================================================
Error executing action `create` on resource 'aws_ebs_volume[db_ebs_volume]'
================================================================================
 
 
RuntimeError
------------
Volume  no longer exists
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache/cookbooks/aws/providers/ebs_volume.rb:189:in `block in create_volume'
/var/lib/aws/opsworks/cache/cookbooks/aws/providers/ebs_volume.rb:177:in `create_volume'
/var/lib/aws/opsworks/cache/cookbooks/aws/providers/ebs_volume.rb:38:in `block (2 levels) in class_from_file'
/var/lib/aws/opsworks/cache/cookbooks/aws/providers/ebs_volume.rb:37:in `block in class_from_file'
 
 
Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache/cookbooks/mongodb/recipes/ebs_backups.rb
 
60: aws_ebs_volume "db_ebs_volume" do
61:   size 7
62:   device "/dev/sdi"
63:   action [ :create, :attach ]
64: end
 
 
Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache/cookbooks/mongodb/recipes/ebs_backups.rb:60:in `from_file'
 
aws_ebs_volume("db_ebs_volume") do
action [:create, :attach]
retries 0
retry_delay 2
cookbook_name "mongodb"
recipe_name "ebs_backups"
size 7
device "/dev/sdi"
timeout 180
volume_type "standard"
piops 0
end
 
 
 
[2014-06-09T16:51:52+00:00] INFO: Running queued delayed notifications before re-raising exception
[2014-06-09T16:51:52+00:00] INFO: template[/etc/default/mongodb] sending restart action to service[mongodb] (delayed)
[2014-06-09T16:51:52+00:00] INFO: Processing service[mongodb] action restart (mongodb::default line 127)
[2014-06-09T16:52:04+00:00] INFO: service[mongodb] restarted
[2014-06-09T16:52:04+00:00] ERROR: Running exception handlers
[2014-06-09T16:52:04+00:00] ERROR: Exception handlers complete
[2014-06-09T16:52:04+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache/chef-stacktrace.out
[2014-06-09T16:52:04+00:00] ERROR: aws_ebs_volume[db_ebs_volume] (mongodb::ebs_backups line 60) had an error: RuntimeError: Volume  no longer exists
[2014-06-09T16:52:05+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Steps to reproduce:

1) create custom recipe
2) add the following code to custom recipe:
```
include_recipe "aws"

aws_ebs_volume "db_ebs_volume" do
  size 7
  device "/dev/sdi"
  action [ :create, :attach ]
end
```

I believe these recipe's are supposed to work with chef-solo but I  haven't been able to use this cookbook to create a volume and attach it to my opsworks instance.  Is this a bug?  Am I doing something wrong?  Any help appreciated!  Thank you!

**Comment by tas50** [comment]
This cookbook will not work properly with Opsworks Chef solo setups and I think it's out of the scope of the cookbook to do the refactoring necessary to support Opsworks.  I'm going to close this out at this point in time.
